dist: focal
language: php
cache:
  directories:
  - $HOME/.composer
  - $HOME/.npm

php:
  - 8.0

env:
  - NODE_VERSION="16.14"

# Make sure we have a recent version of docker-compose and chrome.
addons:
  apt:
    packages:
      - docker-compose
  chrome: stable

mysql:
  database: drupal
  username: root
  encoding: utf8

services:
  - docker

# Add the specified nodejs via nvm, as Travis can only specify a single language.
install:
  - nvm install $NODE_VERSION
  - nvm use $NODE_VERSION
#  - test -n "${SSH_AGENT_PID}" && ssh-agent -k

before_script:
  # Install the AWS CLI and login to the ECR. Credentials are secrets set via the UI.
  - if ! [ -x "$(command -v aws)" ]; then curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" ; unzip awscliv2.zip ; sudo ./aws/install ; fi
  - aws ecr-public get-login-password --region ${AWS_DEFAULT_REGION} | docker login --username AWS --password-stdin public.ecr.aws/unocha

  # Check the docker images we want actually exists.
  - grep 'unocha/unified-builder:' docker/Dockerfile | awk '{print $2}' | xargs docker pull
  - grep 'unocha/php-k8s:' docker/Dockerfile | awk '{print $2}' | xargs docker pull
  # Composer.
  - sed -i '1i export PATH="$HOME/.composer/vendor/bin:$PATH"' $HOME/.bashrc
  - source $HOME/.bashrc
  - composer self-update

  # Ensure the PHP environment is ready.
  - phpenv rehash

  # Code sniff
  - cd $TRAVIS_BUILD_DIR
  - composer install --dev

  # LightHouseBot
  # - npm i --save-dev https://github.com/GoogleChromeLabs/lighthousebot

  # PWMetrics
  # - npm i

script:
  # PHP linting
  - set -e
  - test ! -d ./html/modules/custom || find -L ./html/modules/custom -iregex '.*\.\(php\|module\|inc\|install\)$' -print0 | xargs -0 -n 1 -P 4 php -l
  - test ! -d ./html/themes/custom || find -L ./html/themes/custom -iregex '.*\.\(php\|module\|inc\|install\)$' -print0 | xargs -0 -n 1 -P 4 php -l
  - set +e

  # PHP CS
  - set -e
  - test ! -d ./html/modules/custom || ./vendor/bin/phpcs -p --report=full ./html/modules/custom
  - test ! -d ./html/themes/custom || ./vendor/bin/phpcs -p --report=full ./html/themes/custom
  - set +e

  # Theme build.
  - composer run sass

after_success:
  - cd $TRAVIS_BUILD_DIR
  - killall -9 php

after_failure:
  - echo "The tests failed. Please check the output above for problems."
