minimum_single: 0
minimum_multiple: 0
disable_search_threshold: 0
minimum_width: 0
use_relative_width: false
jquery_selector: 'select, item-list__dropdown'
search_contains: false
disable_search: false
allow_single_deselect: true
placeholder_text_multiple: 'Choose some options'
placeholder_text_single: 'Choose an option'
no_results_text: 'No results match'
max_shown_results: null
disabled_themes:
  seven: '0'
  common_design: '0'
  pocam_common_design: '0'
chosen_include: 2
_core:
  default_config_hash: exRaKE0s6uZbfQrl_2WFEcTlc_1t81xEqCLuCCteUSk
