definitions:
  contact__site_page:
    enabled: false
    menu_name: footer
    parent: ''
    expanded: false
    weight: 0
  user__page:
    menu_name: account
    parent: 'menu_link_content:d3ddc462-02be-4361-814e-89f1169c0fe3'
    weight: -10
    expanded: false
    enabled: true
  node__add_page:
    enabled: false
    menu_name: tools
    parent: ''
    expanded: false
    weight: 0
  standard__front_page:
    enabled: false
    menu_name: main
    parent: ''
    expanded: false
    weight: 0
_core:
  default_config_hash: o4bYR9ZupWb3AsOIizTUG4g-nu1mdJqA59UB7QT-ifQ
