_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
module:
  admin_denied: 0
  automated_cron: 0
  big_pipe: 0
  block: 0
  block_content: 0
  breakpoint: 0
  build_hooks: 0
  ckeditor: 0
  config: 0
  config_split: 0
  contact: 0
  contextual: 0
  ctools: 0
  datetime: 0
  dblog: 0
  devel: 0
  dynamic_entity_reference: 0
  dynamic_page_cache: 0
  editor: 0
  facets: 0
  facets_pretty_paths: 0
  facets_summary: 0
  field: 0
  field_ui: 0
  file: 0
  filter: 0
  google_tag: 0
  help: 0
  history: 0
  image: 0
  layout_builder: 0
  layout_discovery: 0
  link: 0
  maintenance200: 0
  menu_ui: 0
  minimal: 0
  mysql: 0
  node: 0
  options: 0
  page_cache: 0
  path: 0
  path_alias: 0
  pocam_extract: 0
  pocam_general: 0
  quickedit: 0
  rdf: 0
  search_api: 0
  search_api_db: 0
  seckit: 0
  select2: 0
  select2_facets: 0
  shortcut: 0
  simple_sitemap: 0
  social_api: 0
  social_auth: 0
  social_auth_hid: 0
  syslog: 0
  system: 0
  taxonomy: 0
  text: 0
  token: 0
  token_filter: 0
  toolbar: 0
  tour: 0
  update: 0
  upgrade_status: 0
  user: 0
  views_ui: 0
  menu_link_content: 1
  pathauto: 1
  views: 10
theme:
  stable: 0
  classy: 0
  seven: 0
  common_design: 0
  common_design_subtheme: 0
  stark: 0
profile: minimal
