_core:
  default_config_hash: yTxtFqBHnEWxQswuWvkjE8mKw2t8oKuCL1q8KnfHuGE
langcode: en
uuid: b6fc7ae0-4825-4abb-965a-d258fd9f503a
name: 'Aide Memoire'
mail: admin@example.com
slogan: ''
page:
  403: ''
  404: ''
  front: /node/2266
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
