<?php

/**
 * @file
 * POCAM tome.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_pocam_general_build_path_alter().
 */
function pocam_tome_pocam_general_build_path_alter(&$path, array $context) {
  $path = 'internal:/extracts?field_all_themes=' . $context['term']->tid;
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function pocam_tome_form_views_exposed_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if ($form['#id'] == 'views-exposed-form-extracts-page-1') {
    $form['#action'] = '/extracts';
    $form['#method'] = 'get';
  }
}

/**
 * Implements hook_block_build_alter().
 */
function pocam_tome_block_build_alter(array &$build, \Drupal\Core\Block\BlockPluginInterface $block) {
  $id = $block->getDerivativeId();
  if (empty($id)) {
    return;
  }

  $blocks_to_disable = [
    'account',
    'extracts-header',
    'facet_summary',
    'extracts-page_1',
    'document_type',
    'theme',
    'year',
  ];

  if (!in_array($id, $blocks_to_disable)) {
    return;
  }

  $build['#access'] = FALSE;
}
